### ISSUE TITLE
Support building with Expo

### ISSUE THREAD

**Issue by ygit** [100mslive/react-native-hms#442]
`I could not able to install the expo and facing app crash in the application after installing expo.`

**Comment by ygit** [comment]
@Akarsh08 Any updates on this issue? Can you share a doc with steps to have this implemented?

**Comment by ygit** [comment]
```
import HmsManager from '@100mslive/react-native-hms';
const hmsInstance = HmsManager.build();
```

```
Error: Requiring module "node_modules/@100mslive/react-native-hms/src/index.ts", which threw an exception: Invariant Violation: Native module cannot be null.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
```

![Image from iOS](https://user-images.githubusercontent.com/8512357/151921620-67c1e1a3-a933-4671-a6cb-d6ecec2955e7.png)
